# Generated by Django 3.1.3 on 2021-08-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210805_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='label',
            field=models.CharField(default='Test card 1', help_text='User friendly label for the payment method', max_length=255),
            preserve_default=False,
        ),
    ]
