# Generated by Django 3.1.3 on 2021-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210826_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentmethod',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='label',
            field=models.CharField(blank=True, help_text='User friendly label for the payment method', max_length=255, null=True),
        ),
    ]
