# Generated by Django 3.1.3 on 2021-08-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0005_auto_20210624_0333'),
        ('account', '0001_initial'),
        ('orders', '0005_auto_20210805_0426'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_dispatch', models.DateTimeField(blank=True, null=True)),
                ('next_dispatch', models.DateTimeField(blank=True, null=True)),
                ('repeat_period', models.IntegerField(blank=True, help_text='The amount of days until the order is to be repeated', null=True)),
                ('one_click_reminder', models.BooleanField(default=False, help_text='Whether or not to require a customer confirmation before dispatching the order')),
                ('active', models.BooleanField(default=False, help_text='Whether or not this subscription should be dispatched as normal')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='account.account')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.address')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOrderRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.productvariant')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscription')),
            ],
        ),
    ]
