# Generated by Django 3.1.3 on 2021-04-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('account', '0001_initial'),
        ('shipping', '0004_auto_20210408_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_dispatch', models.DateTimeField(blank=True, null=True)),
                ('next_dispatch', models.DateTimeField(blank=True, null=True)),
                ('repeat_period', models.IntegerField(blank=True, help_text='The amount of days until the order is to be repeated', null=True)),
                ('one_click_reminder', models.BooleanField(default=False, help_text='Whether or not to require a customer confirmation before dispatching the order')),
                ('active', models.BooleanField(default=False, help_text='Whether or not this subscription should be dispatched as normal')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Submitted'), (2, 'Fulfilled'), (3, 'Cancelled'), (4, 'Refunded'), (5, 'Payment Failed')], default=1)),
                ('status_note', models.CharField(blank=True, max_length=128, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('shipping_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.address')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_order', to='subscriptions.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptionorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.productvariant')),
            ],
        ),
    ]
