# Generated by Django 3.1.3 on 2021-09-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20210624_0333'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='shipping_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.shippingrate'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dispatch_day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='dispatch_frequency',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Every 2 weeks'), (3, 'Every 3 weeks'), (4, 'Every 4 weeks')], default=1, help_text='The frequency of the order being fulfilled'),
        ),
    ]
