# Generated by Django 3.1.3 on 2021-08-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='dispatch_frequency',
            field=models.IntegerField(default=1, help_text='The frequency of the order being fulfilled, in weeks'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_dispatch',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_dispatch',
            field=models.DateField(blank=True, null=True),
        ),
    ]
