# Generated by Django 3.1.3 on 2021-09-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210908_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionOrderRelation',
        ),
    ]
