# Generated by Django 3.1.3 on 2021-09-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_delete_subscriptionorderrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pause_until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
