# Generated by Django 3.1.3 on 2022-05-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_on_account_title'),
        ('subscriptions', '0004_subscription_pause_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant'),
        ),
    ]
