# Generated by Django 3.1.3 on 2022-06-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220511_1246'),
        ('subscriptions', '0005_auto_20220511_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='account.account'),
        ),
    ]