# Generated by Django 3.1.3 on 2023-03-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221027_1617'),
        ('subscriptions', '0006_auto_20220622_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.productvariant'),
        ),
    ]
