# Generated by Django 3.1.3 on 2021-04-08 22:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type_stream_field',
            field=wagtail.core.fields.StreamField([('percentage', wagtail.core.blocks.StructBlock([('percentage', wagtail.core.blocks.IntegerBlock(help_text='A value between 0 and 100 which represents the percentage discount', max_value=100, min_value=0))])), ('dollar', wagtail.core.blocks.StructBlock([('dollar', wagtail.core.blocks.DecimalBlock(decimal_places=2, help_text='A value with a minimum of 0 which represents a flat dollar discount amount', min_value=0))]))]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='orders.order'),
        ),
    ]
