# Generated by Django 3.1.3 on 2021-09-21 22:14

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20210408_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
