# Generated by Django 3.1.3 on 2021-08-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User friendly name for the payment method', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.paymentmethod')),
                ('stripe_id', models.CharField(max_length=255)),
                ('last4', models.CharField(max_length=255)),
                ('payment_type', models.CharField(help_text='Will most likely be "card"', max_length=255)),
                ('exp_month', models.CharField(max_length=255)),
                ('exp_year', models.CharField(max_length=255)),
            ],
            bases=('account.paymentmethod',),
        ),
        migrations.DeleteModel(
            name='AccountPaymentMethod',
        ),
        migrations.AlterField(
            model_name='account',
            name='active_payment_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.paymentmethod'),
        ),
    ]
