# Generated by Django 3.1.3 on 2021-08-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210811_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Deactivate'), (3, 'Invalid'), (4, 'Expired')], default=(1, 'Active'), help_text='Status to show if the PaymentMethod is active/deactive or otherwise', max_length=255),
        ),
    ]
