# Generated by Django 3.1.3 on 2021-08-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210811_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deactivated'), (3, 'Invalid'), (4, 'Expired')], default=1, help_text='Status to show if the PaymentMethod is active/deactive or otherwise'),
        ),
    ]
