# Generated by Django 3.1.3 on 2021-06-25 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant_ref',
            field=models.CharField(default='placeholder ref', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant_title',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
