# Generated by Django 3.1.3 on 2021-06-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210625_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='base_product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
