# Generated by Django 3.1.2 on 2021-06-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_item_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_order_email',
            field=models.BooleanField(default=False),
        ),
    ]
