# Generated by Django 3.1.3 on 2021-08-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0004_order_item_snapshot_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='account.account'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
