# Generated by Django 3.1.3 on 2022-03-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_subscription_order',
            field=models.BooleanField(default=False),
        ),
    ]
